"""Adicionar relação entre produto e categoria

Revision ID: 1704980e5c3f
Revises: 16695a5a7910
Create Date: 2024-05-10 15:40:15.752702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1704980e5c3f'
down_revision: Union[str, None] = '16695a5a7910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
